# Generated by Django 4.0.6 on 2022-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='related_action',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
