# Generated by Django 4.0.6 on 2022-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_messagedata_related_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='file_message',
            field=models.TextField(default=None),
        ),
    ]
