# Generated by Django 4.0.6 on 2022-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_messagedata_file_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='file_message',
            field=models.TextField(default=None, null=True),
        ),
    ]
