version: "3.3"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    volumes:
      - static_volume:/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/static
  #   ports:
  #     - "80"
  #   depends_on:
  #     - web

volumes:
  postgres_data:
  static_volume:
