apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bot
  labels:
    app: slack-bot
spec:
  selector:
    matchLabels:
      app: slack-bot
  replicas: 3
  template:
    metadata:
      labels:
        app: slack-bot
    spec:
      containers:
        - name: slack-bot
          image: 322454752629.dkr.ecr.us-east-1.amazonaws.com/slack-bot:v1
          ports:
            - containerPort: 8000
              name: slack-bot
          command: ["/bin/sh"]
          args:
            ["-c", "gunicorn slack_bot.wsgi:application --bind 0.0.0.0:8000"]

---
apiVersion: v1
kind: Service
metadata:
  name: slack-bot
  namespace: default
spec:
  selector:
    app: slack-bot
  type: ClusterIP
  ports:
    - name: slack-bot
      protocol: TCP
      port: 8000
      targetPort: 8000
