apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bot-be
  labels:
    app: slack-bot-be
spec:
  selector:
    matchLabels:
      app: slack-bot-be
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slack-bot-be
    spec:
      containers:
        - name: slack-bot-be
          image: 322454752629.dkr.ecr.us-east-1.amazonaws.com/slack-bot:v1
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
